# Generated by Django 3.2.5 on 2021-08-12 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210812_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('validity_from', models.DateField(blank=True, null=True)),
                ('validity_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'leave_type',
            },
        ),
        migrations.CreateModel(
            name='Leave_Restrictions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weekend_bw_leave', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('weekend_bw_leave_days', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('holydays_bw_leave', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('holydays_bw_leave_days', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('exceeds_leave_balance', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('allow_users_to_view', models.CharField(blank=True, max_length=255, null=True)),
                ('balance_to_display', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('minimum_leave_apply', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('maximum_leave_apply', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('maximum_consecutive_leave_apply', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('minimum_gap_apply', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('maximum_application', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
                ('leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.leave_type')),
            ],
            options={
                'db_table': 'leave_resctictions',
            },
        ),
        migrations.CreateModel(
            name='Leave_Effective',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('effective_after', models.CharField(max_length=255)),
                ('effective_period', models.CharField(max_length=255)),
                ('effective_from', models.CharField(max_length=255)),
                ('accrual', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('accrual_period', models.CharField(blank=True, max_length=255, null=True)),
                ('effective_on', models.CharField(blank=True, max_length=255, null=True)),
                ('effective_month', models.CharField(blank=True, max_length=255, null=True)),
                ('effective_no_of_days', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('effective_in', models.CharField(blank=True, max_length=255, null=True)),
                ('reset', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('reset_period', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_on', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_month', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_carry_forward', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('reset_carry_forward_max', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_carry_encashment', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('reset_carry_method', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_encashment_forward_max', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_balance', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('maximum_balance', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
                ('leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.leave_type')),
            ],
            options={
                'db_table': 'leave_effective',
            },
        ),
        migrations.CreateModel(
            name='Leave_Applicable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('source_of_hire', models.CharField(blank=True, max_length=255, null=True)),
                ('onboarding_status', models.CharField(blank=True, max_length=255, null=True)),
                ('all_employees', models.CharField(blank=True, default=1, max_length=255, null=True)),
                ('exception_dept', models.CharField(blank=True, max_length=255, null=True)),
                ('exception_desgn', models.CharField(blank=True, max_length=255, null=True)),
                ('exception_location', models.CharField(blank=True, max_length=255, null=True)),
                ('exception_role', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.PositiveSmallIntegerField(default=1)),
                ('leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.leave_type')),
            ],
            options={
                'db_table': 'leave_applicable',
            },
        ),
    ]
