# Generated by Django 3.2.5 on 2021-08-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_leave_applicable_leave_effective_leave_restrictions_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_type',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leave_type',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leave_type',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
