# Generated by Django 3.2.5 on 2021-08-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210813_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_effective',
            name='reset_carry_forward_overall_limit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
