# Generated by Django 3.2.5 on 2021-08-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210818_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_restrictions',
            name='file_upload_after',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
