# Generated by Django 3.2.5 on 2021-08-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_leave_restrictions_file_upload_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_effective',
            name='reset_carry_forward_expiry_in',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leave_effective',
            name='reset_carry_forward_expiry_month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
