# Generated by Django 3.2.5 on 2021-08-20 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210818_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_effective',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_type_id_effective', to='app.leave_type'),
        ),
    ]
