# Generated by Django 3.2.5 on 2021-08-20 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_leave_effective_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_applicable',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_type_id_applicable', to='app.leave_type'),
        ),
    ]
