# Generated by Django 3.2.5 on 2021-08-24 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_leave_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_applicable',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_type_id_applicable', to='app.leave_type'),
        ),
        migrations.AlterField(
            model_name='leave_effective',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_type_id_effective', to='app.leave_type'),
        ),
        migrations.AlterField(
            model_name='leave_restrictions',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_type_id_restrictions', to='app.leave_type'),
        ),
    ]
