# Generated by Django 3.2.5 on 2021-08-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210824_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_applicable',
            name='exception_emp_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
