# Generated by Django 3.2.5 on 2021-08-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_leave_applicable_exception_emp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_balance',
            name='customize_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
