# Generated by Django 3.2.5 on 2021-09-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_customize_leave_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customize_leave_balance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
